/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721Royalty } from "./ERC721Royalty";
export type { IERC721Metadata } from "./IERC721Metadata";
